/**
 * @file event_loop.hpp
 * @brief Minimal coroutine scheduler backed by `poll(2)`.
 * @ingroup networking
 *
 * The TCP server uses this event loop to avoid a thread-per-connection design.
 * Coroutines explicitly suspend on socket readability or writability; the loop
 * stores the suspended handles and resumes them when `poll(2)` reports the
 * relevant readiness event.
 */
#pragma once

#include <coroutine>
#include <deque>
#include <unordered_map>

namespace net {

/**
 * @brief Cooperative event loop for socket-driven coroutines.
 * @ingroup networking
 *
 * `EventLoop` owns no sockets directly.  It only schedules coroutine handles
 * and records which handle is waiting for which file descriptor.  User code is
 * responsible for closing descriptors when sessions end.
 *
 * @par Scheduling model
 * Ready coroutines are resumed FIFO.  If no coroutine is ready, the loop builds
 * a temporary `pollfd` array from the read/write waiter maps and sleeps in
 * `poll(2)` until the kernel reports progress.
 */
class EventLoop {
public:
    /**
     * @brief Owning wrapper for a coroutine frame scheduled by `EventLoop`.
     *
     * Functions returning `Task` can use `co_await loop.readable(fd)` and
     * `co_await loop.writable(fd)` to suspend until socket readiness.
     */
    class Task {
    public:
        /**
         * @brief Compiler-facing coroutine promise for `Task`.
         *
         * The promise stores the owning loop pointer so final suspension can
         * hand the coroutine frame back to `EventLoop::complete()`.
         */
        struct promise_type {
            /// Owning loop after `Task::start()`; null before the task is spawned.
            EventLoop* loop = nullptr;

            /// Build the public `Task` wrapper around the coroutine frame.
            Task get_return_object() noexcept;

            /// Start suspended so the caller can give the task to a loop first.
            std::suspend_always initial_suspend() noexcept;

            /**
             * @brief Final suspension point that destroys or delegates cleanup.
             */
            struct FinalAwaiter {
                /// Always suspend so cleanup happens in `await_suspend()`.
                bool await_ready() const noexcept;

                /**
                 * @brief Complete a coroutine frame after `co_return`.
                 *
                 * @tparam Promise Promise type generated by the compiler.
                 * @param handle Completed coroutine handle.
                 */
                template <typename Promise>
                void await_suspend(std::coroutine_handle<Promise> handle) const noexcept {
                    if (handle.promise().loop != nullptr) {
                        handle.promise().loop->complete(handle);
                    } else {
                        handle.destroy();
                    }
                }

                /// No value is produced by final suspension.
                void await_resume() const noexcept {}
            };

            /// Return the final awaiter used for controlled frame cleanup.
            FinalAwaiter final_suspend() noexcept;

            /// `Task` coroutines do not produce a result value.
            void return_void() noexcept;

            /// Terminate on uncaught coroutine exceptions.
            void unhandled_exception();
        };

        /// Concrete coroutine handle type for this promise.
        using handle_type = std::coroutine_handle<promise_type>;

        /// Construct an empty task.
        Task() noexcept = default;

        /**
         * @brief Take ownership of a compiler-created coroutine handle.
         * @param handle Coroutine frame to own.
         */
        explicit Task(handle_type handle) noexcept;

        /// Move construction transfers coroutine ownership.
        Task(Task&& other) noexcept;

        /// Move assignment transfers coroutine ownership.
        Task& operator=(Task&& other) noexcept;

        /// Destroy the coroutine frame if the task was never spawned.
        ~Task();

        Task(const Task&) = delete;
        Task& operator=(const Task&) = delete;

        /**
         * @brief Attach this task to an event loop and enqueue it.
         *
         * @param loop Loop that will own the coroutine frame from this point on.
         */
        void start(EventLoop& loop);

    private:
        /// Owned coroutine handle, or null after moving/spawning.
        handle_type handle_ = nullptr;
    };

    /**
     * @brief Awaiter that resumes a coroutine when a descriptor is readable.
     */
    struct ReadAwaiter {
        /// Owning event loop.
        EventLoop* loop = nullptr;

        /// Descriptor to wait on.
        int fd = -1;

        /// Always suspend; readiness is checked by `poll(2)`.
        bool await_ready() const noexcept;

        /// Register the suspended coroutine with the read-waiter map.
        void await_suspend(std::coroutine_handle<> handle) const noexcept;

        /// No result value is produced.
        void await_resume() const noexcept {}
    };

    /**
     * @brief Awaiter that resumes a coroutine when a descriptor is writable.
     */
    struct WriteAwaiter {
        /// Owning event loop.
        EventLoop* loop = nullptr;

        /// Descriptor to wait on.
        int fd = -1;

        /// Always suspend; readiness is checked by `poll(2)`.
        bool await_ready() const noexcept;

        /// Register the suspended coroutine with the write-waiter map.
        void await_suspend(std::coroutine_handle<> handle) const noexcept;

        /// No result value is produced.
        void await_resume() const noexcept {}
    };

    /**
     * @brief Create an awaiter for read readiness.
     * @param fd Descriptor to wait on.
     */
    ReadAwaiter readable(int fd) noexcept;

    /**
     * @brief Create an awaiter for write readiness.
     * @param fd Descriptor to wait on.
     */
    WriteAwaiter writable(int fd) noexcept;

    /**
     * @brief Start a coroutine task on this loop.
     * @param task Task to take over and schedule.
     */
    void spawn(Task&& task);

    /**
     * @brief Enqueue a coroutine handle to resume soon.
     * @param handle Coroutine handle to resume.
     */
    void schedule(std::coroutine_handle<> handle);

    /**
     * @brief Run until stopped or until no coroutines/descriptors remain.
     */
    void run();

    /**
     * @brief Request graceful loop termination.
     *
     * The loop exits after the current ready batch is drained.
     */
    void stop();

    /**
     * @brief Destroy a coroutine frame that has reached final suspension.
     * @param handle Completed coroutine handle.
     */
    void complete(std::coroutine_handle<> handle);

private:
    friend struct ReadAwaiter;
    friend struct WriteAwaiter;

    /// Store `handle` as waiting for readability on `fd`.
    void wait_read(int fd, std::coroutine_handle<> handle);

    /// Store `handle` as waiting for writability on `fd`.
    void wait_write(int fd, std::coroutine_handle<> handle);

    /// Coroutines ready to resume immediately.
    std::deque<std::coroutine_handle<>> ready_;

    /// Coroutines waiting for read readiness, keyed by file descriptor.
    std::unordered_map<int, std::coroutine_handle<>> read_waiters_;

    /// Coroutines waiting for write readiness, keyed by file descriptor.
    std::unordered_map<int, std::coroutine_handle<>> write_waiters_;

    /// Set by `stop()` to request loop exit.
    bool stopping_ = false;
};

}  // namespace net
